name: Checkov

on:
  pull_request:
    branches:
      - main

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          # skip_check: >-
          #   CKV_AZURE_1,
          #   CKV_AZURE_2,
          #   CKV_AZURE_3
