on:
  workflow_call:
    inputs:
      test-filter:
        description: Limit the Terraform Test operation to the specified test files.
        type: string
        required: false

jobs:
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Test
        id: test
        env:
          TF_TEST_FILTER: ${{ inputs.test-filter }}
        run: terraform test -filter="$TF_TEST_FILTER"

      - name: Create job summary
        if: success() || failure()
        shell: bash {0}
        env:
          TF_FMT_OUTCOME: ${{ steps.fmt.outcome }}
          TF_INIT_OUTCOME: ${{ steps.init.outcome }}
          TF_VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
          TF_TEST_OUTCOME: ${{ steps.test.outcome }}
        run: |
          echo "#### Terraform Format and Style 🖌\`$TF_FMT_OUTCOME\`
          #### Terraform Initialization ⚙\`$TF_INIT_OUTCOME\`
          #### Terraform Validation 🤖\`$TF_VALIDATE_OUTCOME\`
          #### Terraform Test 🧪\`$TF_TEST_OUTCOME\`

          *Pusher: @$GITHUB_ACTOR, Action: \`$GITHUB_EVENT_NAME\`, Workflow: \`$GITHUB_WORKFLOW\`*" >> "$GITHUB_STEP_SUMMARY"
